#!/usr/bin/env bash


declare -a blocks
declare -a blocks2
declare -a block_start=(0)
declare -a cntr

while read -r line; do
    for ((i=0; i<${#line}; i++)); do
        block_size=${line:i:1}
        block_start+=("$((${block_start[i]} + block_size))")
        value=
        if (( i%2 == 0 )); then
            value=$((i / 2))
            cntr+=("$block_size")
        else
            value=-1
            cntr+=("0")
        fi
        for (( j=0; j<block_size; j++ )); do
            blocks+=("$value")
        done
    done
done

blocks2=("${blocks[@]}")

ileft=0
iright=$((${#blocks[@]} - 1))
while true; do
    while (( ${blocks[ileft]} >= 0 )); do
        ((ileft++))
    done
    while (( ${blocks[iright]} < 0 )); do
        ((iright--))
    done
    if (( ileft >= iright )); then
        break
    fi
    blocks[$ileft]=${blocks[$iright]}
    blocks[$iright]=-1
done

iright=$((${#cntr[@]} - 1))
while true; do
    ileft=1
    required_space=$(( ${block_start[$((iright+1))]} - ${block_start[iright]} ))
    right=${block_start[$iright]}
    value=${blocks2[$right]}
    while (( ileft < iright)); do
        start=${block_start[ileft]}
        size=$(( ${block_start[$((ileft+1))]} - start ))
        n=${cntr[ileft]}
        free=$((size - n))
        if ((free >= required_space)); then 
            for ((j=0; j<required_space; j++)); do
                blocks2[$((start + n + j))]=$value
                blocks2[$((right + j))]=-1
                cntr[$ileft]=$((cntr[ileft] + 1))
            done
            break
        fi
        ((ileft+=2))
    done
    ((iright-=2))
    if ((iright == 0)); then
        break
    fi
done

part1=0
part2=0
for ((i=0; i<${#blocks[@]}; i++)); do
    if (( ${blocks[$i]} > 0 )); then
        part1=$((part1 + ${blocks[$i]} * i))
    fi
    if (( ${blocks2[$i]} > 0 )); then
        part2=$((part2 + ${blocks2[$i]} * i))
    fi
done

echo "Part 1: $part1"
echo "Part 2: $part2"
