#!/usr/bin/env bash

part1=0
part2=0

declare -A counter

icard=1
while read -r line; do
    for ((i = 0; i < ${#line}; i++)); do
        char="${line:i:1}"
        if [[ "$char" = ":" ]]; then
            line="${line:i+1}"
            break
        fi
    done
    IFS='|' read -r lhs rhs <<<"$line"
    IFS=' ' read -ra winning <<<"$lhs"
    IFS=' ' read -ra hand <<<"$rhs"

    n_winning=0
    ((counter[$icard]++))
    for card in "${hand[@]}"; do
        for win in "${winning[@]}"; do
            if [[ "$card" == "$win" ]]; then
                ((n_winning++))
                break
            fi
        done
    done
    for ((i = 1; i <= n_winning; i++)); do
        ((counter[$((icard + i))] += counter[$icard]))
    done

    if ((n_winning > 0)); then
        ((part1 += 1 << (n_winning - 1)))
    fi
    ((icard++))
done

for cnt in "${counter[@]}"; do
    ((part2 += cnt))
done

echo "Part 1: $part1"
echo "Part 2: $part2"
