#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define STRING_IMPLEMENTATION
#include "string8.h"

#define HASHMAP_IMPLEMENTATION
#include "hash_map.h"

#define VECTOR_IMPLEMENTATION
#include "vector.h"

#include "arena.h"

#define ASKEY(p, n) (((p)[0] << 16) + ((p)[1] << 8) + (n))

typedef uint16_t u16;

void print_cache(hash_map *cache) {
  printf("Cache (capacity: %lu, size: %lu)\n", cache->capacity, cache->size);
  kv_iterator cache_iter = hm_iterator(cache);
  while (get_next(&cache_iter)) {
    u32 key = *(u32 *)cache_iter.key_ptr;
    u8 p0 = key >> 16;
    u8 p1 = key >> 8;
    u8 ngen = key;
    printf("(%c%c, %hu) => {\n", p0, p1, ngen);
    hash_map *hm = *(hash_map **)cache_iter.value_ptr;
    kv_iterator value_iter = hm_iterator(hm);
    while (get_next(&value_iter)) {
      u16 pair = *(u16 *)value_iter.key_ptr;
      u64 n = *(u64 *)value_iter.value_ptr;
      printf("    %c%c => %lu,\n", (u8)(pair >> 8), (u8)pair, n);
    }
    printf("}\n");
  }
}

int cmp_fn(const void *a, const void *b) {
  u64 va = *(u64 *)a;
  u64 vb = *(u64 *)b;
  if (va < vb)
    return -1;
  if (va > vb)
    return 1;
  return 0;
}

void get_generated_pairs(mem_arena *arena, u8 pair[2], u8 ngen, hash_map *rules,
                         hash_map *cache) {
  u32 key = ASKEY(pair, ngen);
  if (hm_contains_key(cache, &key))
    return;

  u16 pair16 = (pair[0] << 8) + pair[1];
  hash_map *next_gen = AUTO_HASHMAP_ARENA(arena, u16, u64);
  if (ngen == 0) {
    u64 n = 1;
    hm_put(next_gen, &pair16, &n);
  } else {
    u8 new_pairs[4];
    u32 n_pair = 0;
    kv_entry rule_entry = hm_get_entry(rules, &pair16);
    if (!rule_entry.found_existing) {
      n_pair = 1;
      new_pairs[0] = pair[0];
      new_pairs[1] = pair[1];
    } else {
      u8 c = *(u8 *)rule_entry.value_ptr;
      n_pair = 2;
      new_pairs[0] = pair[0];
      new_pairs[1] = new_pairs[2] = c;
      new_pairs[3] = pair[1];
    }
    for (u32 ip = 0; ip < n_pair; ++ip) {
      u8 p[2] = {new_pairs[2 * ip + 0], new_pairs[2 * ip + 1]};
      u32 cache_key = ASKEY(p, ngen - 1);
      get_generated_pairs(arena, p, ngen - 1, rules, cache);
      hash_map *cached = HM_GET(hash_map *, cache, &cache_key);
      kv_iterator kvi = hm_iterator(cached);
      while (get_next(&kvi)) {
        u16 cached_key = *(u16 *)kvi.key_ptr;
        kv_entry entry = hm_get_or_put(next_gen, &cached_key);
        u64 cached_value = *(u64 *)kvi.value_ptr;
        u64 *vp = (u64 *)entry.value_ptr;
        if (!entry.found_existing) {
          *vp = 0;
        }
        *vp += cached_value;
      }
    }
  }
  hm_put(cache, &key, &next_gen);
}

int main(int argc, char *argv[]) {
  if (argc < 3) {
    fprintf(stderr, "Usage aoc <file> <ngen>\n");
    return EXIT_FAILURE;
  }

  mem_arena *perm_arena = arena_create(MiB(10));

  string8 file = {0};
  str_read_file(perm_arena, &file, argv[1]);

  // Read lines and get template
  vector *line_vec = VEC_ARENA_CREATE(perm_arena, string8);
  split(line_vec, file, STR8_LIT("\n"));
  string8 *lines = (string8 *)line_vec->data;
  string8 template = lines[0];
  u8 first = template.str[0];
  u8 last = template.str[template.size - 1];

  // Parse rules
  hash_map *rules = AUTO_HASHMAP_ARENA(perm_arena, u16, u8);
  string8 splitted[2] = {0};
  for (u64 i = 2; i < line_vec->size && lines[i].size > 0; ++i) {
    str_split_once(splitted, lines[i], STR8_LIT(" -> "));
    assert(splitted[0].size == 2);
    u16 key = (splitted[0].str[0] << 8) + splitted[0].str[1];
    hm_put(rules, &key, splitted[1].str);
  }

  hash_map *cache = AUTO_HASHMAP_ARENA(perm_arena, u32, hash_map *);
  u8 ngen = atoi(argv[2]);

  // Count letters generated by each pair
  hash_map *lcount = AUTO_HASHMAP_ARENA(perm_arena, u8, u64);
  for (u64 i = 0; i < template.size - 1; ++i) {
    get_generated_pairs(perm_arena, template.str + i, ngen, rules, cache);
    u32 key = ASKEY(template.str + i, ngen);
    hash_map *hm = HM_GET(hash_map *, cache, &key);
    kv_iterator cache_iter = hm_iterator(hm);
    while (get_next(&cache_iter)) {
      u16 pair16 = *(u16 *)cache_iter.key_ptr;
      u64 n = *(u64 *)cache_iter.value_ptr;
      u8 letters[2] = {pair16 >> 8, pair16};
      for (u32 ip = 0; ip < 2; ++ip) {
        kv_entry letter_entry = hm_get_or_put(lcount, letters + ip);
        u64 *vp = (u64 *)letter_entry.value_ptr;
        *vp += n;
      }
    }
  }

  // Divides what needs to be divided by 2
  kv_iterator letter_iter = hm_iterator(lcount);
  u64 *counts = ALLOC_ARRAY(perm_arena, u64, lcount->size);
  u64 indx = 0;
  while (get_next(&letter_iter)) {
    u8 letter = *(u8 *)letter_iter.key_ptr;
    u64 *vptr = (u64 *)letter_iter.value_ptr;
    *vptr /= 2;
    if (letter == first || letter == last)
      (*vptr)++;
    counts[indx++] = *vptr;
  }

  qsort(counts, lcount->size, sizeof(u64), cmp_fn);

  printf("Score: %lu\n", counts[lcount->size - 1] - counts[0]);

  arena_destroy(perm_arena);
}
