#!/usr/bin/env bash

declare -a categories
value=0
while read -r line; do
    if (( ${#line} == 0 )); then
        categories+=("$value")
        value=0
        continue
    fi
    ((value += line))
done
categories+=("$value")

readarray -t sorted< <(printf '%s\n' "${categories[@]}" | sort -nr)

echo "Part 1: ${sorted[0]}"
echo "Part 2: $((sorted[0] + sorted[1] + sorted[2]))"
