#!/usr/bin/env bash

declare -A grid

ntree=0
ny=0
while read -r line; do
    nx="${#line}"
    for ((x = 0; x < nx; ++x)); do
        grid["$ny,$x"]=${line:x:1}
    done
    ((ny++))
done

count-trees() {
    local n_right="$1"
    local n_down="$2"
    local x=0
    local y=0
    ntree=0
    while ((y < ny)); do
        if [[ "${grid["$y,$x"]}" == "#" ]]; then
            ((ntree++))
        fi
        ((x = (x + n_right) % nx))
        ((y += n_down))
    done
}

count-trees 3 1
echo "Part 1: $ntree"

slopes=("1,1" "3,1" "5,1" "7,1" "1,2")
part2=1
for slope in "${slopes[@]}"; do
    IFS="," read -r right down <<<"$slope"
    count-trees "$right" "$down"
    ((part2 *= ntree))
done

echo "Part 2: $part2"
