#!/usr/bin/env bash

prev=
declare -a values=(0 0 0)

part1=0
part2=0
line=0
sum1=0
sum2=0
while read -r depth; do
    ((line > 0 && depth > prev)) && ((part1++))
    prev="$depth"
    for ((i = 0; i < 3; i++)); do
        ((line < i)) || ((values[i] += depth))
    done
    ((line++))
    ((line < 3)) && continue
    sum1="$sum2"
    sum2="${values[0]}"
    values=("${values[1]}" "${values[2]}" 0)
    ((line > 3 && sum2 > sum1)) && ((part2++))
done

echo "Part 1: $part1"
echo "Part 2: $part2"
