#!/usr/bin/env bash

floor=0
part2=-1

while read -r line; do
    for ((i = 0; i < ${#line}; ++i)); do
        c="${line:i:1}"
        case "$c" in 
            '(')
                ((floor++))
                ;;
            ')')
                if ((floor == 0 && part2 == -1)); then
                    part2=$((i+1))
                fi
                ((floor--))
                ;;
        esac
    done
done

echo "Part 1: $floor"
echo "Part 2: $part2"
