#!/usr/bin/env bash

declare -A lexec

lexec["Python"]="./day06.py"
lexec["Rust"]="./target/release/day06"
lexec["Go"]="./goday06"
lexec["C"]="./day06"
lexec["Zig"]="./run06"
lexec["Bash"]="./tuning-trouble"

for lang in "${!lexec[@]}"; do
    echo "-- $lang --"
    if [[ "$lang" == "Bash" ]]; then
        time "${lexec[$lang]}" < "input"
    else
        time "${lexec[$lang]}" input
    fi
done
