#!/usr/bin/env bash

found=
packet_start=

check-if-countains() {
    found=0
    local word="$1"
    local letter="$2"
    local i
    for ((i = 0; i < ${#word}; i++)); do
        if [[ "${word:i:1}" == "$letter" ]]; then
            found=1
            return
        fi
    done
}

find-packet-start() {
    local input="$1"
    local wsize="$2"
    local n="${#input}"
    local i j
    packet_start=-1
    for ((i = 0; i < n - wsize; i++)); do
        local is_packet_start=1
        for ((j = 1; j < wsize; j++)); do
            local word=${input:i:j}
            check-if-countains "$word" "${input:i+j:1}"
            if ((found)); then
                is_packet_start=0
                break
            fi
        done
        if ((is_packet_start)); then
            ((packet_start = i + wsize))
            return
        fi
    done
}

while read -r line; do
    find-packet-start "$line" 4
    echo "Part 1: $packet_start"
    find-packet-start "$line" 14
    echo "Part 2: $packet_start"
done
