#!/usr/bin/env bash

declare -A digits

digits["one"]=1
digits["two"]=2
digits["three"]=3
digits["four"]=4
digits["five"]=5
digits["six"]=6
digits["seven"]=7
digits["eight"]=8
digits["nine"]=9

total1=0

while read -r line; do
    n=${#line}
    left=-1
    for (( i=0; i<n; i++ )); do
        if [[ ${line:i:1} =~ ^[0-9]+$ ]]; then
            left=${line:i:1}
            break
        fi
        subarray=${line::i+1}
        for key in "${!digits[@]}"; do
            if grep -q $key <<< "$subarray"; then
                left=${digits[$key]}
                break
            fi
        done
        if (( left != -1 )); then
            break
        fi
    done
    right=-1
    for (( i=n-1; i>=0; i-- )); do
        if [[ ${line:i:1} =~ ^[0-9]+$ ]]; then
            right=${line:i:1}
            break
        fi
        subarray=${line:i:n}
        for key in "${!digits[@]}"; do
            if grep -q $key <<< "$subarray"; then
                right=${digits[$key]}
                break
            fi
        done
        if (( right != -1 )); then
            break
        fi
    done
    if (( left == -1 || right == -1 )); then
        echo "Something went wrong"
        exit 1
    fi
    total1=$((total1+left*10+right))
done

echo $total1
