#!/usr/bin/env bash

total1=0
total2=0

while read -r line; do
    read -a numbers <<< "$line"
    prev=0
    next=0
    factor=1
    while true; do
       n=${#numbers[@]}
       new_values=()
       next=$((next+numbers[n-1]))
       prev=$((prev+factor*numbers[0]))
       factor=$((factor*(-1)))
       stop=true
       for (( i=0; i<n-1; i++ )); do
           diff=$((numbers[i+1] - numbers[i]))
           new_values+=($diff)
           if (( diff != 0 )); then
               stop=false
           fi
       done
       if [[ $stop == true ]]; then
           break
       fi
       numbers=("${new_values[@]}")
    done
    total1=$((total1+next))
    total2=$((total2+prev))
done

echo "Part 1: $total1"
echo "Part 2: $total2"
